### ISSUE TITLE
Rectification and Filtering Procedures

### ISSUE THREAD

**Issue by ykukkim** [GallVp/emgGO#1]
Dear Rashid,

Your emgGo is an awesome work and definitely helpful, but there are some parts I do not quite understand. If you could help me out, this will be helpful!

In the paper published(2.2.1) 

> This rectified signal was then passed through a moving average filter with **a window length of Lb seconds**. Using this moving average of the rectified signal, **a baseline segment of length Lb** seconds was selected from the rectified  sEMG signal such that the rank of the corresponding moving average was **Kbth**

1. Where is the rectification of the signal performed? is it here?

`https://github.com/ykuk0906/emgGO/blob/2d19ea978428883178cba1faa9f39aca6b88ad63/emgEventsDetectTool.m#L337-L343`

In addition, it is said that it is passed through a moving average filter but in the code, I cannot quite find where this is happening, could you point it out to me perhaps?

2. **The length of Lb seconds** is mentioned twice, **a window length** and **a baseline segment of length Lb**,  I do not quite understand how the value of Lb is selected, for the **window length** is it the length of the data or do you arbitrarily choose the value? if so, where is this carried out?

3. Lastly, 

>  the rank of the corresponding moving average was **Kbth**

I assume this is performed in **filterstream()**, where **Butterworth filter** and **filtfilt() **is carried out twice.  However, I do not quite understand the steps of the process. How do you determine the value of K? is this the coefficient we get after running the **filtfilt()?** 

`https://github.com/ykuk0906/emgGO/blob/2d19ea978428883178cba1faa9f39aca6b88ad63/Helpers/filterStream.m#L35-L41`

Thank you for your help in advance!

**Comment by GallVp** [comment]
Thank you for raising this issue.

I have tried to answer the highlighted questions in a new markdown document here: https://github.com/GallVp/emgGO/blob/master/docs/edtaExplained.md

Go through the document to see if it answers your questions. I can add additional information if you have more questions.

It would be a great help if you highlight any spelling or other mistake, correct it and add a pull request.

**Comment by ykukkim** [comment]
Thank you for your work again.

Your explanation does an amazing job for people to start!

It is unfortunate that I could not spot any mistake in your explanation or so, I am sure others may be able to spot it!

I do however another few questions, your script runs on the single-channel source, which works fine with my data to in conditions of correct modifications.

For my data, I had to modify a bit, the highlighted bits are where I had to add in order to get the **baselinemean** and **std**. Weirdly, the index for IA is retrieved in random order, does this matter? as your data gives ordered IA. I had to times by 10000 as my EMG is not amplified much as your value.

`UNIQUE_TOL = 1/max(abs(inputSignal*10000)); 
[~, IA, ~] = uniquetol(movingAverage, UNIQUE_TOL);
**IA = sort(IA);**`

Also, with I rounded my index for baselineinterval  too, but you don't seem to do it and works fine. Is there a reason why you didn't use round for this?

`baselineInterval = startSampleNo - floor(baselineLength/2) + 1 : startSampleNo + floor(baselineLength/2);
**baselineInterval = round(baselineInterval);**`

Lastly, have you tried with multichannel data? I was wondering if the value of **baseline mean and **std** were calculated for each channel.  If you look at my data(14 channel), the first channel does detect the activation very well but for other channels, it doesn't seem to do so. 

If I am not very clear, please let me know. 
Thank you for your work!

![1](https://user-images.githubusercontent.com/25555933/62109846-1c644180-b2e8-11e9-86fb-e9e142dd25b4.JPG)
![2](https://user-images.githubusercontent.com/25555933/62109847-1c644180-b2e8-11e9-907e-ed314d95d937.JPG)
![3](https://user-images.githubusercontent.com/25555933/62109848-1c644180-b2e8-11e9-9ca7-620f2aa67541.JPG)
![4](https://user-images.githubusercontent.com/25555933/62109849-1cfcd800-b2e8-11e9-884b-6c07b15c415e.JPG)
![5](https://user-images.githubusercontent.com/25555933/62109851-1cfcd800-b2e8-11e9-9e95-c87a708d4843.JPG)
![6](https://user-images.githubusercontent.com/25555933/62109852-1d956e80-b2e8-11e9-8c05-0af29387bad9.JPG)

**Comment by GallVp** [comment]
A few notes:
1. uniquetol returns a rank order of the signal by comparing values. For example, consider the following code.
```MATLAB
[~, IA, ~] = uniquetol([10 5 1 8], 0.1)
IA =

     3
     2
     4
     1
```

IA is the rank order of [10 5 1 8] in ascending order. Using `sort` on IA destroys the rank order.

2. The value of UNIQUE_TOL also created problems for me. If you can share your data via email, I can look at the problem and maybe change the way UNIQUE_TOL is calculated so that it works across datasets.

3. I am rounding the `baselineLength` parameter using the sampling rate in the `extendedDTA` function. If you need to round `baselineInterval`, then there is bug in my code as rounding should not be required.

4. Yes, I have tested the toolbox on multi-channel data. The `extendedDTA` function only works on single channel but the GUIs are designed to work on multi-channel data by running the `extendedDTA` on each channel individually. The GUIs keep parameters separate for each channel.

5. I would suggest to use the *nOptim* based Auto Find function to detect onsets/offsets. But if you are trying to go through the ins and outs of the algorithm, then tuning the parameters manually is of course what you need to do. This requires tuning parameters for each channel separately as in my experience same parameters rarely work for all the channels.

**Comment by ykukkim** [comment]
I will send you the link where my data is stored via email. I personally believe that the value of **UNIQUE_TOL** is creating a problem which leads onto other functions hence not able to get correct detection of bursts.

Regards to your comment on **extendedDTA** function only working on a single channel and manually adjusting the parameters using GUI. Please correct me if I am wrong, but as far as I understand, values for **OptionsVector** should not vary between channels as the behaviour of muscle activation are quite similar.

Please let me know,

Thank you!

**Comment by GallVp** [comment]
Thank you for your help in identifying a number of bugs in the toolbox. Please download the latest version with the bugs fixed. Two of the fixed bugs are:

1. UNIQUE_TOL has been removed and a simpler logic is now used. For further details, please see issue no [2](https://github.com/GallVp/emgGO/issues/2).

2. By default, `emgEventsDetectTool` initialises same parameters for all the channels. If a parameter is changed for the selected channel, this does not affect the remaining channels. This was done as in some situations, different channels need different parameters. But you are right, there are situations when same parameters are required. To cater to such situations, I have added an additional button "Apply to all". By pressing this button, the current parameters are applied across all the channels, thus, saving time in copy pasting parameters manually.
