### ISSUE TITLE
Pipeline for Process

### ISSUE THREAD

**Issue by ykukkim** [GallVp/emgGO#6]
Dear Usman,

I am not too sure whether I am correct with this problem, but using the edit function may only work for one channel of EMG. 

For instance, I have four channels of EMG to edit and if this can be manually adjusted on **emgEventsDetectTool** as the **vars.channelNum** gets updated for **emgEventsManageTool** hence having only one index for https://github.com/GallVp/emgGO/blob/2e71bc9404a4c009ce65d7f4a41bc20ca0d1e8b8/emgEventsManageTool.m#L75

However, in **editFunc** the processed data is fed in meaning that a number of channels are fed at once. Meaning that https://github.com/GallVp/emgGO/blob/2e71bc9404a4c009ce65d7f4a41bc20ca0d1e8b8/emgEventsManageTool.m#L75, the Index exceeds the number of array elements as vars.eventMarkerY only has value for the first channel.

Do you know how to go on about this problem?

Please let me know,

Thank you,

Kind regards,

Yong Kim

**Comment by GallVp** [comment]
Hi Yong Kim

Can you kindly confirm that you have the latest version of emgGO, with the latest commit from 2 days ago?

Thank you

**Comment by ykukkim** [comment]
Hi!

Oh, I now have used the latest version of emgGO, and now it works! 

WIll have to look at it in detail how it works!

Thank you!
